name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gkrellm libgtk2.0-dev nvidia-cuda-toolkit
      - name: Build plugin
        run: make
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: gkrellm-gpu-plugin
          path: build/gkrellm-gpu.so
